### ISSUE TITLE
Questions about the results on MMVet

### ISSUE THREAD

**Issue by vva1024** [pipilurj/bootstrapped-preference-optimization-BPO-#10]
Hi! 

I found the 7B [ckpt](https://huggingface.co/renjiepi/BPO-Lora-LLaVA-7B) file you provided in a previous issue. After running my tests, I obtained the following results. Could you help me figure out why there is such a discrepancy between these results and the results reported in the paper? I used the testing code provided by the official llava scripts. 

Thank you for your assistance!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/fuyh/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/fuyh/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

rec | ocr | know | gen | spat | math | total | std | runs |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
37.3 | 26.9 | 20 | 23.7 | 29.6 | 9.2 | 33.3 | 0 | [np.float64(33.3)]

</body>

</html>

**Comment by pipilurj** [comment]
Hi, thanks a lot for your interest. Please try to reinstall the packages provided in the current repo. The score achieved by huggingface checkpoint should be around 36.0, the slight different should be due to different batchsizes and number of GPUs I used. However, 33.3 may indicate either something is wrong with the inference code, or the package versions are incorrect.

**Comment by htzhang-code** [comment]
> Ok, I will try it again. Thanks for your reply. I will update my situation ASAP.

Hello, have you solved this issue? I had the same.

**Comment by htzhang-code** [comment]
> > Ok, I will try it again. Thanks for your reply. I will update my situation ASAP.
> 
> Hello, have you solved this issue? I had the same.

It has been solved. The cause was that clip-vit-large-patch14 was specified incorrectly as clip-vit-large-patch14-336 in the local path.
