### ISSUE TITLE
error running the script

### ISSUE THREAD

**Issue by Artanic30** [pipilurj/bootstrapped-preference-optimization-BPO-#7]
Hi, thanks for your great work! I'm trying to run this code base and encounter some issues. For example, in `llava/train/bpo_llava.py` line946,
```
    collator = LLaVADPODataCollator(data_args=data_args, tokenizer=tokenizer, max_length=1024)
```
the following error shows up
```
TypeError: DPODataCollatorWithPadding.__init__() got an unexpected keyword argument 'tokenizer'
```
Could you kindly provide the specific version of *trl* or how to install *trl* ?

**Comment by Artanic30** [comment]
I managed to solve the issue by installing 
```
trl==0.7.2
transformers==4.31.0
```
I hope the authors could verify the versions and update the requirements.

**Comment by pipilurj** [comment]
Thanks a lot! We added the dependencies in the installation file.

**Comment by htzhang-code** [comment]
Hello, I would like to ask what options are there for argument --model_name_or_path?
